### ISSUE TITLE
Any planned updates here?

### ISSUE THREAD

**Issue by htelsiz** [memetic-institute/The-Fed#1]
This is dope. Let me know if you want some help on your next project.

**Comment by NPC64927130** [comment]
We've mostly completed this game, but there are definitely things we'd like to go back and fix/enhance if we have the time. So no updates planned, but maybe someday.

And thanks for offering some help! We've got a couple different concepts brewing, so we'll reach out if we need some more hands on-deck.

**Comment by MichaelWalker-git** [comment]
This is a hilarious project. Nice job dude.
